### ISSUE TITLE
Improve Renovate bot configuration on this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/parser-utils#31]
#### What

Standardize and improve our Renovate bot setup.

#### Why

We're not consistent with the setup we use on this repository, compared to the setup we have on the main renovate bot repo.

In any case we're missing these things that I think are important/handy to have:

- We're not extending from our global `renovatebot/.github` Renovate config
- Wait 3 days until getting updates for npm packages (can be unpublished within 72 hours)
- Pin GitHub Actions to SHA / Digest

We also have some overly large groups, not sure what we want to do with them:

https://github.com/renovatebot/parser-utils/blob/ba1ea2afff2155f86e74b4cdbc1934e4517d9a3b/renovate.json#L10-L40

I also don't like how the bot adds labels, our other Renovate bot PRs do not add any labels, so we might want to strip the labeling part out of the config as well.

#### How

Discuss what changes we want/need to our Renovate config on this repository.
Make PR to make the changes.

**Comment by HonkingGoose** [comment]
@rarkins @zharinov What do you think you want/need Renovate bot do to on this repository?

**Comment by viceice** [comment]
This is now using our shared preset, so closing this.

**Comment by zharinov** [comment]
BTW, this repository is superseded by [zharinov/good-enough-parser](https://github.com/zharinov/good-enough-parser/)
